### ISSUE TITLE
Error: Running LUA method 'update'

### ISSUE THREAD

**Issue by Kamuhoro** [modelleicher/FS19_simpleIC#1]
```
2020-01-26` 19:21 Error: Running LUA method 'update'.
2020-01-26 19:21 C:/Users/smaeg/Documents/My Games/FarmingSimulator2019/mods/FS19_simpleIC/simpleIC.lua:292: attempt to index a nil value
```

[log.txt](https://github.com/modelleicher/FS19_simpleIC/files/4114027/log.txt)

Version: 0.9.1.3

Issue: IC could not be toggled neither from indoors, nor outdoors. Worked again after reentering the tractor. Occurred in MP.

Steps to reproduce: unknown (did not occur again afterwards)

Side note: potential mod conflict? Also several faulty mods were in use

**Comment by modelleicher** [comment]
Hello,

line 292 is this one
if not self:getActiveCamera().isInside then

So the error means that self:getActiveCamera() was nil, which is impossible while you're inside a vehicle (its a default game function) I assume either a mod conflict or somehow your client didn't register you entering the vehicle.

**Comment by modelleicher** [comment]
Jetzt ist der Fehler jedenfalls abgefangen, warum das nil sein kann keine Ahnung, aber nu machts keine Probleme mehr ;)
