### ISSUE TITLE
Courseplay

### ISSUE THREAD

**Issue by Bandesss** [modelleicher/FS19_simpleIC#16]
Leider spackt die Steuerung mit Courseplay
Kann mir jemand verraten wie er das in Griff bekommen hat.
Ich öffne CP mit der rechten maus taste, aber dann wackelt der maus zeiger und ich kann nichts einstellen.
Danke für die Hilfe

**Comment by modelleicher** [comment]
Hallo,
Mit der aktuellesten Version von Courseplay und der aktuellsten Version von SimpleIC kann ich das Problem nicht reproduzieren. Allerdings hab ich das klassische Problem der Doppelbelegung, dass sich entweder SimpleIC oder Courseplay nicht mehr bedienen lässt.
Das liegt leider an Courseplay, die Taste "CP: Maus-Aktion" ist Grundsätzlich aktiv und default auf die linke Maustaste belegt, das blockiert dann alles andere was ebenfalls auf die linke Maustaste belegt ist.
Schau dieses Video bezüglich Doppelbelegungen:
https://youtu.be/Zfe00-PSruA
Die einzige Lösung ist entweder die Taste für IC oder die Taste für Courseplay auf ne andere Taste zu belegen.

Wie gesagt das flackern konnte ich so nicht reproduzieren. Welche Version von Courseplay und welche Versioon von SimpleIC verwendest du, und hast du schon mal nur mit den beiden Mods probiert, vielleicht steuert da ja noch ein dritter Mod dazwischen.

LG

**Comment by Bandesss** [comment]
Wir haben den Mod acro 1000 von Agram Modding Ader hat auch eine Ic Steuerung kann es daran liegen? Es gibt zusätzliche ic Befehle in den Tastatur Einstellungen
