### ISSUE TITLE
Click on icon

### ISSUE THREAD

**Issue by DrDrulia** [modelleicher/FS19_simpleIC#19]
Hello. First want to say amazing job. I edited my first tractor yesterday. Amazing. Couple questions. Can I replace click on “X” to something else or make it smaller? 
Thanks 🙏 
Dr. Drulia

**Comment by modelleicher** [comment]
Hello,
Currently no.
The "X" is a text-symbol so no Icon/image file. As of right now, it's hard coded in the script. I plan on making it customizable in the future so you can add your own text in the XML. But no Icons/Images as that does not work with the simple/easy way simpleIC works.
So in the future you could replace it with an "O" or any other text-based symbol. I also plan on adding a scale factor ;) 
So both of these features are on the list but I can't promise which update will bring them.

**Comment by DrDrulia** [comment]
Thanks for respond and I will wait for update
