### ISSUE TITLE
Simple IC not working at all?

### ISSUE THREAD

**Issue by MetalGovy** [modelleicher/FS19_simpleIC#2]
Hi i just downloaded simple ic to give it a try.
I downloaded it together with your deutz fahr mod.
But when the x in the game pops up and i click on it nothing happens?
Its a clean folder with only these two mods inside it:

FS19_deutzAgroStar661_ModelleicherEdit.zip
FS19_simpleIC.zip

This is my logfile: https://pastebin.com/pK0t49fs

**Comment by Flo707** [comment]
have you assigned the keys?

**Comment by MetalGovy** [comment]
> have you assigned the keys?

Do i have to do this manually?
If so how to ?

**Comment by Flo707** [comment]
In the options :)

![F4FC3B99-F73E-4F1D-9D6B-11F2F46C4303](https://user-images.githubusercontent.com/38164274/73308836-67242f00-4221-11ea-8b4a-d050ff301b47.png)

![96A40F8D-A91B-4C7C-A07F-974EC188F13B](https://user-images.githubusercontent.com/38164274/73308837-67242f00-4221-11ea-88d3-c8f63e5e3d40.png)

**Comment by MetalGovy** [comment]
Ah thank you.
I didn't know that cause the readme didnt say this.

**Comment by Flo707** [comment]
No Problem :)
