### ISSUE TITLE
letztes Update vom 19/03

### ISSUE THREAD

**Issue by cabmac** [modelleicher/FS19_simpleIC#22]
Moin, das letzte update funkioniert bei mir jedenfalls nicht mehr. Ich sehe zwar die Punkte zum aber es tut sich nichts mehr beim anklicken. Vorherige Version wieder rein, alles in Ordnung...K.A. ob das nur bei mir so ist?

Schoene Gruesse

Claudio

**Comment by modelleicher** [comment]
Moin,
Ist nicht nur bei dir so. Spiel bis dahin wieder mit der vorherigen Version ;) 
Für Leute die vorher Probleme mit Doppelbelegung hatten fixt die aktuelle Version das unter Umständen, dafür machts bei Leuten die vorher keine Probleme hatten jetzt Probleme.

Also am besten die vorherige Version spielen wenn man vorher keine Probleme hatte, bis ich das gefixt hab :) 

LG

**Comment by FarmerMike87** [comment]
Hallo kann ich mir hier ne vorherige version iwo runterladen??? ich IDIOT hab die überschrieben 👎

**Comment by cabmac** [comment]
auf" Commits " hast du alle Versionen

**Comment by FarmerMike87** [comment]
Vielen Dank das hab ich mich scho oft gefragt wo ältere Versionen sind 👍

**Comment by cabmac** [comment]
Moin..0.9.1.9. funktioniert nun bei mir...

Vielen Dank,

LG
