### ISSUE TITLE
Heckhydraulik von außen per simpleIC absenken

### ISSUE THREAD

**Issue by oschuhm** [modelleicher/FS19_simpleIC#27]
Hallo,
kann ich irgendwie meine Heckhydraulik von außen per simpleIC absenken?
Leider vergesse ich das mit manualAttach öfter und muss dann wieder einsteigen und die Hydraulik abzusenken.
Würde lieber einen der Knöpfe hinten via simpleIC benutzen.
Hoffe Du kannst mir weiterhelfen.
VG
Olli

**Comment by modelleicher** [comment]
Hallo,
Derzeit noch nicht aber ist auf jeden Fall geplant dass man Anbaugeräte per SimpleIC heben/senken kann selbstverständlich geht das dann auch von außen ;) 

LG

**Comment by oschuhm** [comment]
Hi,
vielen Dank für die schnelle Antwort.
Wenn ich bei Entwicklung / Test unterstützen kann dann sag bitte Bescheid.
Bin ja beruflich in der Ecke unterwegs.
VG
Olli

**Comment by oschuhm** [comment]
Hallo modelleicher,
ich habe mir mal die Funktion mit der Hydraulik in Dein Script eingebaut.
Es funktioniert prima im SinglePlayer und auch wenn ich alleine auf dem Server im MultiPlayer bin.
Sobald eine zweite Person dazukommt geht es nicht mehr.
Weißt Du ob es irgendwo eine Doku gibt was ich beachten muß wenn die Scripte auf dem Server laufen sollen? Das ist bestimmt nur ein Sync Problem :(
Fehler im Log gibt es keine.
Hier noch der Link zu einem Beispielvideo: https://drive.google.com/open?id=1LL9L5IIrGA-UyXY1v_XlqhtxWPyySmeX
VG
Oliver

**Comment by modelleicher** [comment]
Im Multiplayer muss alles synchronisiert werden, zum einen in den onReadStream/onWriteStream Funktionen zum anderen per Event wenn das tatsächliche Event eintritt.

LG

**Comment by oschuhm** [comment]
Hi,
gibt es da irgendwo eine Doku für?
LG

**Comment by modelleicher** [comment]
Nicht direkt, aber in jedem Script das ein User-Input hat und Multiplayer-Tauglich ist findet sich mindestens ein Event und alles was dazu gehört ;) Z.b. direkt in SimpleIC

**Comment by rooftopbbq** [comment]
@oschuhm Servus. Könntest Du mir verraten wie Du das mit simpleIC gelöst hast? Würde gerne im Innenraum des Traktors mein Güllefass bedienen und Lichter schaltbar machen.

**Comment by oschuhm** [comment]
@rooftopbbq Na klar, ich habe neue Funktionen geschrieben und in simpleIC registriert die in der Lage sind die Hydraulik hinten bzw vorne zu heben / senken / aktivieren.
Das habe ich nochmal neu implementiert und die Funktionen genutzt die das Standard Spiel hier zur Verfügung stellt. Den ganzen Sync Kram mit Server und co übernimmt jetzt das Standard Spiel.
Dann arbeitet simpleIC ja über Animationen.
Ich habe hier einfach gesagt, dass wenn bestimmte Animationen gestartet werden sollen, dass er dann nicht die Animation startet sondern die entsprechende Funktion für die Hydraulik aufruft.
Das wars schon.
Das aktivieren vom Güllefaß könnte man dann auf einen simpleIC Trigger im Innenraum legen.
Die Lichter müsste man doch auch schon jetzt über eine Animation Triggern können ... da bin ich mir allerdings nicht sicher. Das habe ich so noch nicht gemacht.

**Comment by schuelli238** [comment]
Die beiden Deutz von FBM machen auch verdammt viel mehr mit SimpleIC, als ich bisher kannte.
Richtig geil!
Die kann man sich mal ansehen und lernen.
https://forbidden-mods.de/filebase/file/6551-fbm-team-deutz-serie-7-ttv/

**Comment by rooftopbbq** [comment]
@oschuhm Bin ja absoluter Anfänger was das modden bzw scripten angeht. Jetzt muss ich nur noch rausfinden wie man das alles hinbekommt. Hättest Du vielleicht ein Code-Beispiel damit ich verstehen kann wie man das ganze angehen muss?

**Comment by oschuhm** [comment]
@rooftopbbq Die Funktion um die Anbaugeräte an der Heckhydraulik zu aktivieren schaut z.B. so aus:
`function simpleIC:activateRearMachine()

	if debug > 1 then print("DEBUG: simpleIC -> new activateRearMachine() called") end
	
    simpleIC:enumerateAttachments(self)
	
	for _, object in pairs(implements_back) do
		if object[1].spec_turnOnVehicle ~= nil then
			local isTurnedOn = object[1]:getIsTurnedOn()
			object[1]:setIsTurnedOn(not isTurnedOn) -- this toggles
		end
	end
end	`

Die Funktion um die Anbaugeräte an der Heckhydraulik anzuheben schaut so aus:
`function simpleIC:upperBackHydraulicLSF()

	if debug > 1 then print("DEBUG: simpleIC -> new upperBackHydraulic() called") end
	
	simpleIC:enumerateAttachments(self)
	
	for _, objectBack in pairs(implements_back) do

        local attacherJointDescBack = objectBack[2]
        if debug > 1 then print("DEBUG: simpleIC_LSF -> attacherJointDescBack = "..tostring(attacherJointDescBack)) end

		local moveDown = not objectBack[1]:getIsLowered()
		if debug > 1 then print("DEBUG: simpleIC_LSF -> objectBack:getIsLowered() = "..tostring(objectBack[1]:getIsLowered())) end
		if debug > 1 then print("DEBUG: simpleIC_LSF -> can be moved down = "..tostring(moveDown)) end
    
        if not moveDown then
			objectBack[1]:setLoweredAll(moveDown, attacherJointDescBack)
		else
			if debug > 1 then print("DEBUG: simpleIC_LSF -> back hydraulic is already up") end
		end
	end
	
end`

Und dann musst Du noch den Teil in simpleIC anpassen wo die einzelnen Animationen aufgerufen werden
`...
elseif animation.animationName == "activateBack" then
		self:activateRearMachine();
...`

**Comment by rooftopbbq** [comment]
@oschuhm Vielen Dank. Dann werde ich mich mal daran versuchen. 1000 Dank

**Comment by rooftopbbq** [comment]
@oschuhm Die ersten beiden Funktionen werden in die simpleIC.lua eingebaut?

**Comment by oschuhm** [comment]
> 
> 
> @oschuhm Die ersten beiden Funktionen werden in die simpleIC.lua eingebaut?

@rooftopbbq Die Änderungen werden alle in der simpleIC.lua gemacht.

**Comment by rooftopbbq** [comment]
Danke. Es läuft. Sehr geil.

**Comment by oschuhm** [comment]
> 
> 
> Danke. Es läuft. Sehr geil.

Sehr schön.
Wenn Du das mit den paar Codeschnippseln hinbekommen hast ... dann bist Du aber bestimmt schon kein absoluter Anfänger mehr und hast bestimmt irgendwo schon mal was mit Scriptsprachen zu tun gehabt :)
Oder Du bist ein Naturtalent. Dann mach bitte genau an der Stelle weiter :)

**Comment by rooftopbbq** [comment]
@oschuhm habe 2001 mal Fach-Abi Informationstechnik gemacht. C und Assembler. Dann mal bisschen ASP und Java gemacht. Bin da aber schon eeewig raus aus dem Thema.
Jetzt will ich mal schauen ob ich es hinbekomme Lichter per simpleIC zu schalten.

Vorher muss ich aber aus meinem Fendt das IC ausbauen.

**Comment by Valentohallon** [comment]
@oschum wo in der Lua baut man die Funktion ein? Auch die wo man die Animation hernimt? 
bin noch relativ neu in der Modding szene.

**Comment by Masterbaiter1337** [comment]
Hi @oschuhm kannst du mir vllt mal die XML von dem Fahrzeug zeigen ? habe keine ahnung wie ich die Animation in der xml schreiben soll. 

MFG Niklas

**Comment by oschuhm** [comment]
Hi Niklas,
in der XML selbst muß keine Animation geschrieben werden.

Im Teil für simpleIC hinterlegt Du dann lediglich einen Pseudo Animationsnamen.
Der muss aber nicht existieren.

`	<simpleIC outsideInteractionTrigger="sIC_playerTrigger" >
		<animation animationName="doorLeftMovement" animationSpeed="1" sharedAnimation="false" soundVolumeIncreasePercentage="10.0" >
			<outsideTrigger triggerPoint="sIC_doorLeftOutside" triggerPointSize="0.04" />
			<insideTrigger triggerPoint="sIC_doorLeftInside" triggerPointSize="0.04" />
		</animation>
		<animation animationName="windowBackMovement" animationSpeed="1.5" sharedAnimation="false" soundVolumeIncreasePercentage="10.0" >
			<insideTrigger triggerPoint="sIC_windowBackInside" triggerPointSize="0.04" />
		</animation>
		
		
		
		<animation animationName="lowerBackHydraulic">
			<outsideTrigger triggerPoint="sIC_rearAttacherDown" triggerPointSize="0.01" />
		</animation>
		<animation animationName="upperBackHydraulic">
			<outsideTrigger triggerPoint="sIC_rearAttacherUp" triggerPointSize="0.01" />
		</animation>
		
	    <cylinderAnimations>
		    <cylinder node1="rearWindowLeftCylinder" node2="rearWindowLeftCylinderInside" />
			<cylinder node1="rearWindowRightCylinder" node2="rearWindowRightCylinderInside" />
	    </cylinderAnimations>
		
	</simpleIC>`

VG
Olli

**Comment by Masterbaiter1337** [comment]
@oschuhm hi Danke für die schnelle Antwort.. habe das problem das ich nicht ganz zurecht komme mit Diesem Teil -> Und dann musst Du noch den Teil in simpleIC anpassen wo die einzelnen Animationen aufgerufen werden
... elseif animation.animationName == "activateBack" then self:activateRearMachine(); ... <-  habe leider keine erfahrung in diesem bereicht und weiß deswegen nicht was ich and der SimpleIC lua ändern soll bzw was ich da einfügen soll

**Comment by oschuhm** [comment]
Hi Niklas,
das wäre der Teil hier.
Kann man bestimmt noch schöner machen ... tut es aber erst mal.
![grafik](https://user-images.githubusercontent.com/20269675/91299910-afe59b80-e7a2-11ea-8ae0-37f7e81d65c8.png)
Da simpleIC aus der Feder des lieben modelleichers stammt und nicht auf meinem Mist gewachsen ist, möchte ich das fertige Script nicht rausgeben. Zumal das auch noch auf einer Version 0.9.1.9 aufbaut. Einen Merge auf die aktuelle Version habe ich nicht gemacht.
LG
Olli

**Comment by Masterbaiter1337** [comment]
Vielen Dank :) das hilft mir schon bisschen weiter MFG Niklas

**Comment by Masterbaiter1337** [comment]
Ich weiß nicht was ich falsch machen aber es will einfach nicht Funktionieren....
![78e2b32a3b9e8d65dd58a0a640c901f2](https://user-images.githubusercontent.com/70265587/91303530-71eb7600-e7a8-11ea-9784-3ad863cdcac5.png) bin denke ich mal bisschen zu doof dafür :)

**Comment by oschuhm** [comment]
Auf welcher simpleIC Version baust Du denn auf?
Ich habe keine Ahnung ob die Code Schnipsel noch zu einem simpleIC > 0.9.1.9 passen da ich es selbst noch nicht gemerged habe.
Grundsätzlich hilft aber hier die log.txt zu lesen ... und einen Fehler nach dem anderen zu reparieren.

Alternativ würde ich hier vorschlagen zu warten bis der @modelleicher diese Funktionalität implementiert hat. Es ist ja schon als "Enhancement" gekennzeichnet.

VG
Olli

**Comment by picsbyruhrpott** [comment]
@oschuhm wo baust du was in der lua ein weil ich komm mit den fitzeln bzw fotos nicht zurecht
