### ISSUE TITLE
Zusatz Feature: Manuelles Ankoppeln

### ISSUE THREAD

**Issue by Fuzzy86** [modelleicher/FS19_simpleIC#3]
Hey! Die neue IC Steuerung ist echt nice. Wenn das irgendwie machbar wäre, wäre es geil wenn man mit dieser Steuerung auch Geräte manuell An und Abkoppeln könnte. 

Lg

**Comment by modelleicher** [comment]
Hi,
Du meinst von außen? Dafür gibts doch den "manuelles ankuppeln" Mod von Wopster? ;) 

LG
