### ISSUE TITLE
PlayerTrigger vergrößern

### ISSUE THREAD

**Issue by schuelli238** [modelleicher/FS19_simpleIC#32]
Hallo SimpleIC-Team und Community,

GREAT JOB so far :-)
Ich bin noch realativ neu im GE, aber die ersten umbauten auf Simple IC haben super geklappt. Bei einem 900er Fendt ist der Playertrigger aber fast zu klein, wenn die Tür geöffnet ist.
Wie kann ich den Playertrigger vergrößern?
Nutze aktuell den Trigger, den @modelleicher unter seinem Erklärungsvideo verlinkt hatte.

Viele Grüße
Andre

**Comment by modelleicher** [comment]
Hallo,

Um einen Trigger zu skalieren machst du folgendes
1. notierst du dir die Settings die der Trigger bei Rigid Body hat(oder behälst ne Kopie)
2. haken bei "Rigid Body" raus nehmen
3. Trigger skalieren
4. Edit -> Freeze Transfomations und da "scale" wählen
5. haken bei "Rigid Body" wieder rein machen
6. vorher notierte Settings wieder einstellen

LG

**Comment by schuelli238** [comment]
Works like a charm! 
Danke dir @modelleicher :-)
