### ISSUE TITLE
sIC Auf dedi server

### ISSUE THREAD

**Issue by Danny6150r** [modelleicher/FS19_simpleIC#39]
Hallo habe das Problem dass simple IC auf meinem dedi server nicht funktioniert ich habe den Mod hochgeladen sowie den Trecker der mit simple ic ausgerüstet ist ich kann weder in den trecker einsteigen noch Simple ic benutzen.

Bitte im hilfe

**Comment by TethysSaturn** [comment]
Hallo, ich kann den Bug auf dem Dedi Server bestätigen (getestet mit v0.9.2.0 und v0.9.2.1). Der Bug tritt ab v0.9.2.0 auf, v0.9.1.9 läuft einwandfrei. Keinerlei Fehler im SP oder beim gehosteten Spiel. Das Logfile zeigt keinen Fehler an.

**Comment by modelleicher** [comment]
Hmm.. Dann ist das wohl nicht durch das verursacht was ich in der 0.9.2.1 gefixt habe.

**Comment by CCL1106** [comment]
kann ich mir die 0.9.1.9 irgendwo noch laden?

**Comment by modelleicher** [comment]
Hier auf Github auf die Commits klicken dann auf den Hash und dann auf "Browse Files" kommst du in die jeweilige Version

LG
