### ISSUE TITLE
Kamera wechsel und IC 0.9.2.0

### ISSUE THREAD

**Issue by Borsti95** [modelleicher/FS19_simpleIC#40]
Moin nachdem ich ein wechsel von der Version 0.9.1.3 zu 0.9.2.0 machte viel mir erst mal auf das die Controller steuerung taste A für innen nicht mehr ging. Konnte ich aber beheben. Es gab eine Belegungs Kollision mit der Anhängen  steuerung was ich aber gelöscht habe wegen manual attaching, das hatte 0.9.1.3 nicht. 

Das zweite ist nach einem Cam wechsel von außen nach innen geht leider IC nicht mehr egal ob controller oder tastatur. Ich muss wieder ein und außsteigen.

Was ich witzig fand war das wenn ein anderer Schlepper neben einem anderen steht das die türen beider schlepper nicht mehr von außen aufzumachen sind via IC. Eigentlich war da genug platzt. Beide schlepper haben IC. 

Aber so ist der Mod fantastisch und eine weiter entwicklung den 17er IC vor allem wegen der steuerung via controller. Tolle sache. Mach weiter so

**Comment by modelleicher** [comment]
Man kann nicht in mehreren Triggern gleichzeitig stehen, wenn du zwischen beiden Schleppern stehst und somit in beiden Triggern dann geht unter Umständen keiner von beiden.

Die andere Sache bin ich mir nicht sicher ob das ein Bug ist oder ein Modkonflikt, ich würde fast auf letzteres vermuten, allerdings haben mehrere das Problem.
Hast du mal ohne andere Mods ein Savegame gestartet und geschaut ob es dann immer noch ist? 

LG

**Comment by TobiAs1995** [comment]
Ich werde das gleich mal probiereb ob es ein bug oder Konflikt ist.
Ok das mit den triggern ist logisch
Dank dir

**Comment by TobiAs1995** [comment]
Habe es gerade getestet mit nur den nur den Farmer 309ci und IC im modrdner. Dasselbe nochmal mit 600er LSA von Polofreak und einem Ursus C360 um einen Fehler in den Mods auszuschließen (man weiß ja nie). Leider das selbe Ergebnis. Es muss sich dann wohl leider um einen Bug handeln.  

LG Tobias (Borsti)

**Comment by modelleicher** [comment]
Hmm.. das wird lustig zu finden scheint ja nicht bei jedem aufzutreten. Muss ich mal schauen wie ich das reproduzieren kann

**Comment by TobiAs1995** [comment]
Ok. Ich drücke dir die alle Daumen.
und bleib Gesund
LG

**Comment by modelleicher** [comment]
Besteht der Fehler in der aktuellen Version immer noch? MP oder SP?

LG
