### ISSUE TITLE
'packetReceived' errors in MP

### ISSUE THREAD

**Issue by KITT3000** [modelleicher/FS19_simpleIC#45]
Today there were bugs from SimpleIC, the first problem was that when the host was in the vehicle with this mod, the client could not join the game (syncization did not end, there was an error of one of the main game scripts, FSBaseMission or similar), when in finally I managed to sync in LOG there was an error from SimpleIC (different at the host and different at the client, I attach both LOGs).

[log_host.txt](https://github.com/modelleicher/FS19_simpleIC/files/4589361/log_host.txt)
[log_client.txt](https://github.com/modelleicher/FS19_simpleIC/files/4589360/log_client.txt)

**Comment by modelleicher** [comment]
Hi, I hope I fixed this issue with the current version (0.9.2.2) but not 100% sure since I don't have a dedicated server to test at the moment. But I think its the same issue people have been having because I had the indexing wrong. It worked fine as long as only implements with one input attacher were on the savegame but if you have something hat has multiple it messed up the indexing. 
So this should be fixed now.. I hope. I'm not sure how it can be related to if somebody is in a vehicle or not. So maybe it didn't fix it.. :( 
 Please report back :)

**Comment by Bandesss** [comment]
Hallo wir haben weiterhin fehler im MP
Neueste Version
[log.txt](https://github.com/modelleicher/FS19_simpleIC/files/4600665/log.txt)

**Comment by KITT3000** [comment]
One error disappeared, but another appeared. When the host (my friend creates the server) is in the vehicle or terrain editing mode the client (me) cannot join the game, this error occurs:
`Error: Running LUA method 'packetReceived'.
2020-05-10 11:35 mods/MP_UserB4D/FS19_simpleIC/simpleIC.lua:193: attempt to index a nil value
2020-05-10 11:35 Error: Running LUA method 'update'.
2020-05-10 11:35 dataS/scripts/FSBaseMission.lua(1980) : attempt to index field 'player' (a nil value)`
(this game script generates an error all the time)

On the host, however, this error appears all the time when the client joins the game:
`Error: Running LUA method 'packetReceived'.
2020-05-10 11:31 C:/Users/Adam/Documents/My Games/FarmingSimulator2019/mods/FS19_simpleIC/simpleIC_implementBalls.lua:102: attempt to index a nil value`

**Comment by LLLOOOMMM** [comment]
Guten Abend,
wir haben den Fehler auch auf unserem Dedicated-Server. Folgende Probleme konnte ich bisher beobachten:
- Sycro dauert teilweise ewig
- In Fahrzeug mit simpleIC kann nicht eingestiegen werden.

Version: 0.9.2.2

Grüße
Max Jung

**Comment by DerMicha23** [comment]
wir haben das gleiche problem seit der v:9.2.0 das man nicht in den fahrzeugen einsteigen kann die mit  simpleIC sind im singelpiayer geht alles

**Comment by modelleicher** [comment]
Could be fixed with 0.9.2.3, ran on our server no issues, though I did not test with a full mods folder just a few mods.
please report back :) 

@DerMicha23 @LLLOOOMMM Könnte mit 0.9.2.3 gefixt sein zumindest bei uns aufm Server fehlerfrei gelaufen.

**Comment by DerMicha23** [comment]
danke werden es am wochenende testen

**Comment by KITT3000** [comment]
Problem solved
