### ISSUE TITLE
simpleIC_implementBalls.lua:102

### ISSUE THREAD

**Issue by Maximilian2508** [modelleicher/FS19_simpleIC#46]
Hallo,

seit dem ich die neuste Version (0.9.2.1) runtergeladen habe kriege ich beim Starten eines Spielstands folgenden Error: 
Error: Running LUA method 'loadSharedI3DFileFinished'.
C:/Users/Maximilian/Documents/My Games/FarmingSimulator2019/mods/FS19_simpleIC/simpleIC_implementBalls.lua:102: attempt to index a nil value

Kann mir jemand sagen woran das liegt, wie ich das behoben bekomme oder ob das überhaubt an simple IC liegt? Log ist angehangen.

LG und Danke im Vorraus.

[log.txt](https://github.com/modelleicher/FS19_simpleIC/files/4592677/log.txt)

**Comment by modelleicher** [comment]
Hallo,
Den Fehler haben viele, aber mir ist es bisher nicht gelungen den Fehler zu reproduzieren. Ist das im Singleplayer? 
Kannst du mal alle anderen Mods testweise deaktivieren?

LG

**Comment by modelleicher** [comment]
Bitte mit der aktuellen Version (0.9.2.2) erneut testen :)

**Comment by Maximilian2508** [comment]
Hallo,

ich habe gestern es nochmal probiert und da ich auf der Hof Bergmann Spiele habe ich alles was mit Global Company zu tun hat aus dem Mod Ordner entfernt und da hat es Funktioniert. Vielleicht hat es mit Global Company zu tun?? Und ich werde es jetzt mal mit der neuen Version probieren und auch einmal ohne sonstige mods.

LG

**Comment by Maximilian2508** [comment]
@modelleicher 

Ich hab es jetzt nochmal ohne mods nur mit dem Deutz 6.61 Rebuild von dir und Simple IC in der neuen Version (0.9.2.2) probiert und da hat alles ohne probleme Funktioniert. Auch wieder im Singleplayer.

**Comment by Fab7331** [comment]
im MP bleibt das problem

**Comment by modelleicher** [comment]
Sollte jetzt auch im MP alles gehen

**Comment by BlackTron09** [comment]
Guten Morgen,
bei uns auf Server kommt der Fehler auch im Multiplayer trotz neuer Version.
2020-10-03 10:01 Error: Running LUA method 'packetReceived'.
2020-10-03 10:01 C:/Users/Administrator/Documents/My Games/FarmingSimulator2019/mods/FS19_simpleIC/simpleIC_implementBalls.lua:102: attempt to index a nil value
2020-10-03 10:01 Error: Running LUA method 'packetReceived'.
2020-10-03 10:01 C:/Users/Administrator/Documents/My Games/FarmingSimulator2019/mods/FS19_simpleIC/simpleIC_implementBalls.lua:102: attempt to index a nil value

Aktuellste Version 0.9.2.3

[log.txt](https://github.com/modelleicher/FS19_simpleIC/files/5321301/log.txt)
