### ISSUE TITLE
Simple IC mit Head Tracking

### ISSUE THREAD

**Issue by lemsim2** [modelleicher/FS19_simpleIC#50]
Hallo erstmal,
vielen Dank erstmal für deine super Arbeit. Mal eine Frage, ich nutze Simple IC und nutze ein Head Tracking System, es ist ja so, das wenn ich im Fahrzeug sitze muss ich mit dem Headtracking (Kopfbewegungen) das Kreuz auf das X bringen und dann mit drücken der Maustaste zum Bespiel die Tür zu öffnen. Das ist manchmal etwas fummelig oder zum Beispiel bei der Heckscheibe, wenn da das Kreuz genau hinter dem Fahrersitz liegt kann ich den Kopf gar nicht so weit drehen das das Kreuz über dem X liegt. Bei dem Mod IHC 554-644 ist ja ein eigenes IC Script eingebaut, bei dem funktioniert das so das man zwar mit dem Headtracking in Richtung des Punktes schaut, aber sobald man das IC Aktiviert, kann man dann mit der Maus den Cursor steuern und den Punkt Beispiel Tür öffnen aktivieren. Dann kann man mit dem Headtracking die Kamera bewegen und mit der Maus das Kreuz zum aktivieren. Wäre das beim Simple IC auch möglich? Hoffe man versteht worauf ich hinaus will.
Vielen Dank für deine super Arbeit und deine tollen Videos, weiter so

Beste Grüße

**Comment by jonaslinhose** [comment]
hi.. ich kann mich nur anschließen: klasse Script und jeder Mod wird bei mir auf dieses Script umgerüstet.. 
Aber das mit dem HeadTracking kann ich nur bestätigen, es ist eine wunderbare Konzentrations- und Körperübung den Kopf so ruhig zu halten das man so manches X auch drift.. also wenn es dafür eine Lösung gibt wäre es super... andernfalls muss man sich halt zusammen reißen ;).

**Comment by modelleicher** [comment]
Hallo,
Das ist ja das alte IC Script das es seit LS09 geht, wo die Kamera einfriert und die Maus beweglich wird sobald man IC aktiviert.
Das hat mir noch nie gefallen und hab ich bewusst anders gemacht bei SimpleIC ;) 

Anfangs war es geplant dass man auf die andere Version umschalten kann für die, die das wollen, aber dadurch dass ich so viele Probleme mit den Doppelbelegungen hatte hab ich mich dann dafür entschieden allen unnötigen "Ballast" wie verschiedene Modi und ein Menü aus SimpleIC zu entfernen sodass es wirklich simple und basic ist ;) 

Mal schauen ob ich irgendwann wieder so was einbaue, die meisten Leute die ich kenne die mit Headtracking spielen hatten bisher noch keine Probleme damit.

LG

**Comment by jonaslinhose** [comment]
Vielen dank für die ausführliche Antwort und ich habe damit auch kein wirkliches Problem... Es geht, man muss sich nur konzentrieren... Also kein stress und keine Mühe... Ist ja so schon eine klasse Sache mit dem Script.

**Comment by lemsim2** [comment]
Hallo, 
danke für deine Antwort. Ist ja auch nicht das mega Problem so wie es ist, ist so ja schon ein tolles Script. Ich würde es super finden und finde es eine klasse Idee, wenn man umschalten könnte wie man es haben will, da wäre für jeden das richtige dabei. Würde mich sehr freuen wenn es irgendwann mal so kommen würde. Vielen Dank nochmal für die super Arbeit die du für alle LS Spieler leistest 
Beste Grüße

**Comment by lemsim2** [comment]
Eins will ich doch nochmal eben loswerden, hatte ich vorhin vergessen. Wenn man das von der Realismus Seite sieht, finde ich es so wie es im alten IC Script war auch etwas realistischer, weil im echten Leben muss ich ja auch den Türgriff nicht mit meinem Blick hundertprozentig fokussieren um ihn zu bestätigen. Da finde ich es wenn man mit Headtracking spielt schon besser dahin zu gucken, und dann mit der Maus wie mit dem Arm/Hand zu betätigen. Aber das ist auch nur meine Meinung die ich mal loswerden wollte. Schönen Sonntag allen noch.

**Comment by modelleicher** [comment]
In echt hat man aber 2 Hände und keine Maus und man kann den Kopf drehen.. ;) 
Dass die Kamera einfriert hat mich halt immer gestört, weil in echt ist die Handbewegung nicht von der Kopfbewegung abhängig, so hat man dann immer angefangen sich umzuschauen, gefreezed für die Maus, gesucht wo man mit der Maus grade ist, geklickt, wieder losgelassen.. 
Mag sein dass das vom Workflow her mit Headtracking anders ist, aber ohne Headtracking hat sich das für mich halt immer sehr den Spielfluss "unterbrechend" angefühlt und auch umständlich/lange gedauert.. Bin mehr als einmal wo dagegen gefahren während ich mit IC was aufmachen wollte :D 

Daher für mich fühlt sich das so realistischer/intuitiver an auch wenn man natürlich in echt nicht direkt auf was drauf starren muss um es zu bedienen.. 
Wobei man natürlich in Real schon oft genau da hin starrt wo man hingreift für den Moment wo man hingreift ;) 

LG

**Comment by lemsim2** [comment]
Ja da gebe ich dir natürlich auch recht. Wahrscheinlich haben beide Ansichten seine Richtigkeit :D. Daher deine Idee mit dem umschalten was du erst vor gehabt hättest, wäre natürlich super, da hätte jeder was ihm gefällt. Ich lass mich überraschen was da noch so von dir kommt und freue mich drauf. 
Beste Grüße
