### ISSUE TITLE
ptoControl

### ISSUE THREAD

**Issue by Liam-0408** [modelleicher/FS19_simpleIC#63]
Hi ich würde gerne mit simpleIC die pto steuern, welchen attacherindex muss ich da verwenden? den attacherJointBack? wäre nett wenn mir jemand hilft

**Comment by modelleicher** [comment]
Hi, der "XML-Index" des Attachers, wie für die Schema-Overlays oder ptoConfigurations
![attacherJointIndices](https://user-images.githubusercontent.com/7594383/100801197-ef69f680-3427-11eb-8410-4976eb8a66d5.jpg)

**Comment by Liam-0408** [comment]
Danke, aber welchen muss ich da nehmen?

**Comment by modelleicher** [comment]
Den für den Attacher an dem das Gerät hängt das du einschalten willst

**Comment by Liam-0408** [comment]
Sprich für einen ladewagen z.B den trailerattacherjointback 
Und für ein heckmähwerk den attacherjointback
Oder? 
Danke für die Infos

**Comment by modelleicher** [comment]
jup

**Comment by Liam-0408** [comment]
Danke 😉

**Comment by Liam-0408** [comment]
Moin, bei mir will die ptocontrol einfach nicht gehen:

<ptoControl attacherIndex="attacherJointBack" >
			<leverAnimation animationName="leverAnimationPTO" doNotSynch="false" />
			<insideTrigger triggerPoint="0>12|1|1" triggerPointSize="0.04" />		
		</ptoControl>

Hab ich da einen fehler enthalten? der IC-Triggerpoint wird mir angezeigt, ganz falsch ist es also nicht
Danke schonmal

**Comment by Flo707** [comment]
du musst den attacherIndex angeben.

Sam hat es dir oben in dem Foto sper markiert.

du hast mit "attacherJointBack" die node angegeben, nicht den Index.
schau auf Sam's Foto oben hat er dir die Indexe auf der linken Seite mit grün und rot markiert und nummeriert.
Sprich in deinem Fall ist "attacherJointBack" ---> "1"

**Comment by Liam-0408** [comment]
ach so, deshalb sind davor die Zahlen! Danke, probiere ich gleich mal

**Comment by Flo707** [comment]
und wenn du soweit bist probierst du bitte Version 0.9.3.2 und die Vorgänger-Version 0.9.3.1
Bei mir funktioniert mit Versin 0.9.3.2 die ptoControl nicht mehr, bei der Vorgänger-Version klappt alles wie es soll bei mir.

Wenn bei dir Version 0.9.3.2 auch nicht gehen sollte bitte bei meinem Issue bestätigen, damit Sam Info's hierfür hat :)

**Comment by Liam-0408** [comment]
Habs bei der 0.9.3.1 probiert, geht!

**Comment by Flo707** [comment]
Dann kannst du jetzt auch ptoControl einbauen :)

Dann könntest du ja deine "gelösten" Fehler schließen dass für Sam einwenig Übersichtlichkeit einkehrt :)

**Comment by Liam-0408** [comment]
Ja maxh ich danke ^^
