### ISSUE TITLE
seit 0.9.3.2 funktioniert ptoControl nicht mehr

### ISSUE THREAD

**Issue by Flo707** [modelleicher/FS19_simpleIC#65]
seit 0.9.3.2 funktioniert die ptoControl nicht mehr, bei 0.9.3.1 funktioniert alles wie es soll.

Kein Fehler in der Log.

**Comment by Liam-0408** [comment]
Ich habe das Problem leider auch, bei der 0.9.3.1 funktioniert alles

**Comment by Flo707** [comment]
mit 0.9.3.3 funktioniert wieder alles(getestet im SP), vielen Dank Sam :)
