### ISSUE TITLE
Simple IC funktioniert nach Außenbenutzung, innen nicht mehr.

### ISSUE THREAD

**Issue by CaptainADK** [modelleicher/FS19_simpleIC#70]
Hallo liebe Ls19/Fs19 Spielerinnen/Spieler,

ich benutze Simple IC schon sehr lange (okay ein Jahr ist für mache weinig), aber ich musste mich immer mit dem Problem rumkämpfen, dass Simple IC, nachdem ich außen etwas benutzt habe, ich innen nichts mehr anklicken konnte. Das einzige, das dann noch half war das Spiel neuzustarten oder das Fahrzeug zurückzusetzen und nichts mehr von außen zu bedienen. Jetzt wollte ich Mal endlich fragen, ob es dazu eine Lösung gibt. Coursplay ist zwar installiert aber das einzige was eine Doppelbelegung hat ist die linke Maustaste (Habe es aber auch schon ausprobiert mit den anderen Maustasten). Ach und alle Fahrzeuge die das normale IC verwenden habe ich auch deinstalliert.
Ich hoffe das mir einer Helfen kann und bedanke mich schonmal im voraus.

Mit freundlichen Grüßen
CaptainADK

**Comment by modelleicher** [comment]
Hallo,
Probier mal nur SimpleIC und einen Mod in dem SimpleIC verbaut ist auf nem Spielstand ohne andere Mods und schau ob es dann geht.
Meine Vermutung geht entweder auf Doppelbelegung die erst nach dem Kamera switchen aktiv wird oder auf einen Konflikt z.b. mit Abschleppstange/Abschleppgewicht Mods, das Script ist bekannt dass es für einige Konflikte sorgt unter anderem dafür dass sich SimpleIC im Innenraum nicht mehr bedienen lässt.

LG

**Comment by MauriceDrescher** [comment]
Richtig. Es liegt an Doppelbelegung. Ich habe dieses Problem auch gehabt und immer wieder ausprobiert, bis ich dann gemerkt habe, dass es an Doppelbelegung liegt.

**Comment by CaptainADK** [comment]
Okay ich werde es mal ausprobieren, da ich aber in meinen Modordnern Ordnung geschafft habe hoffe ich das sich das Problem vielleicht schon gelöst hat.

Mfg Captain ADK

P.S. Danke für die Hilfe

**Comment by CaptainADK** [comment]
Hallo,

ich bin es seit langer Zeit wieder. Ich hatte in den letzten Monaten ein Ls19 Tief. Auf jeden Fall habe ich mich mal drangesetzt und habe herausgefunden dass Courseplay und Simple IC Probleme machen. (Von beiden gerade erst die neuste Version heruntergeladen.) Wie oben schon angemerkt liegt es wahrscheinlich an einer Doppelbelegung nur wie soll ich das ändern oder besser gefragt wie soll ich jetzt vorgehen?

MfG CaptainADK 
[log.txt](https://github.com/modelleicher/FS19_simpleIC/files/6063272/log.txt)

**Comment by CaptainADK** [comment]
Ach und die Wage und Verkaufsstation habe damit nichts zu tun das habe ich schon ausprobiert die habe ich nur auf der Karte platziert. Deswegen habe ich sie drin gelassen.

**Comment by CaptainADK** [comment]
Habe es geschafft. Juhu. Es war einen Doppelbelegung ich musste einfach von CP  den Reiter "Maus-Aktion" auf eine andere Maus Taste legen und fertig das witzige dabei ist, dass man trotzdem im CP Menü mit er linken Maustaste navigieren kann und somit sich nicht umgewöhnen muss. Danke an alle die geholfen haben.

MfG CaptainADK
