### ISSUE TITLE
Pochende/farblich abstimmenden Punkte statt Kreuze

### ISSUE THREAD

**Issue by fs19maxs** [modelleicher/FS19_simpleIC#75]
Hallo Sam, 

Ich habe mich schon des längeren gefragt ob es dir möglich wäre, für das Script kleine pochende Punkte statt der Kreuze mit Farbwahl (Jeweilige Farbcodes in der Moddesc oder XML des Mods einstellbar) möglich ist.
Seit den Neuerungen finde ich persönlich das die Kreuze sehr dominierend im Innenraum geworden sind, sei es bei meinen oder anderen Mods.

Wiederum finde ich allerdings auch, dass man für ein perfektes Spielerlebnis nicht auf die Funktionen verzichten kann!

Oder hast du kurz und knapp einen passenden LUA Code um die Kreuze für sich selber gegen Punkte zu tauschen?

beste Grüße
Max‘s

**Comment by modelleicher** [comment]
Hallo, die Kreuze sind Text über renderText entsprechend kann man die theoretisch gegen alles tauschen was ein Zeichen/Zahl/Buchstaben ist. Allerdings eben keine Decals wie das in den alten IC Versionen der Fall war. Das macht es m.M. nach deutlich komplizierter für den Einbau / bin ich kein Fan von ;) 

Eines Tages wollte ich das noch anpassen dass man für jede Funktion spezifisch bestimmen kann was für ein Zeichen angezeigt wird, außerdem die Größe der Zeichen einstellbar. Aber eins nach dem anderen.. 

Ob pochende/animierte Punkte so hilfreich wären gegen das dominieren der Punkte bezweifel ich jetzt aber bisschen  ;) 

LG

**Comment by fs19maxs** [comment]
Moin, 

vielen dank für diese weit ausgeholte Antwort!
Das ganze klingt super und ich freue mich darauf.

Auf das bezogene Pochen kam ich über den Zweig von C&C.

beste Grüße
Max's
