### ISSUE TITLE
Simple IC und TrackIR

### ISSUE THREAD

**Issue by Black4Howk** [modelleicher/FS19_simpleIC#8]
Moin Sam, erstmal vielen Dank für die tolle Umsetzung. Ich spiele gern aus der Innenansicht und nutze dafür auch die TrackIR Funktion/Unterstützung des Spieles.
Als erstes, habe ich Tastenbelegung in den Optionen so belegt, dass ich die mittlere Maustaste  zum ein und ausschalten des IC nutze und zu dem noch die Linke Taste zum bestätigen  der Funktion. Dieses funktioniert ohne TrackIR super wenn die Innenkamera mit der Maus gesteuert wird. Im TrackIR Modus, wird die Innenkamera vom der MausSteuerung übergeben ... So kann ich mit dem Kopf die Tür anvisieren und das Kreuz ❌ erscheint auch, jedoch reagiert er dann nicht auf mein Linksklick um diese zu öffnen.

Hättest Du eine Idee?
Wie kann ich dich hierbei unterstützen?

Viele Grüße SpassAmDaddelnTV /Alex

**Comment by modelleicher** [comment]
Hallo,
Es gibt einige die SimpleIC mit TrackIR spielen ohne Probleme, kann also nicht direkt damit zu tun haben.
Wird das X auch rot wenn du drüber bist mit dem Fokus?
Wenn das X rot wird dann wird erkannt dass du dich mit dem Fokus über dem X befindest, wenn durch klicken der Taste aber trotzdem nichts passiert liegt das höchstwahrscheinlich an der Taste.
Kann es sein dass die linke Maustaste für irgend etwas anderes verwendet wird wenn TrackIR aktiv ist, oder dass du zufällig nen Mod mit drin hattest der die linke Maustaste verwendet? 

Leider gibt es immer Probleme mit den Doppelbelegungen, so schlimm dass ich Zeitweise darüber nachgedacht habe den Mod gar nicht zu veröffentlichen. Fixen kann ich das leider nicht, weil es ein Problem von Giants ist..

Drum wär meine Vermutung zuerst mal dass es sich auch hier um ein Doppelbelegungs-Problem handelt? 

LG

**Comment by Black4Howk** [comment]
Moin Sam, gut, ich prüfe das noch mal und geb noch mal Rückmeldung. Danke

**Comment by Black4Howk** [comment]
Moin Sam, Du hattest recht, es lag an einer Doppelten Tastenbelegung🤪.
Vielen Dank noch mal... und Grüße
