### ISSUE TITLE
Funktioniert nur von außen(Doppelbelegung beachtet)

### ISSUE THREAD

**Issue by N0ah16** [modelleicher/FS19_simpleIC#80]
Hallo Modelleicher, 
mein Problem ist, dass eigentlich alles funktioniert, solange ich die Tasten auf die linke Maustaste festlege. Doch wenn Courseplay dazu kommt, liegt wieder die Doppelbelegung vor.  Wenn ich nun IC auf andere Tasten lege um dies zu umgehen, funktioniert es nur von außen, während ich von innen, immer neu einsteigen muss, wenn ich IC abgeschaltet habe, damit es wieder funktioniert egal auf welcher Taste. Woran liegt das?

**Comment by GogsDS** [comment]
Moin!
Das gleiche Problem bei mir, sobald ich es aus- und wieder einschalte, funktioniert es nicht!

**Comment by modelleicher** [comment]
Hallo, das klingt merkwürdig. Habt ihr eine Abschleppstange/Abschleppgewicht drin bzw. ein Mod der das Abschleppscript nutzt? Klingt ähnlich wie der daher bekannte Konflikt

**Comment by N0ah16** [comment]
Ne selbst wenn ich alle Mods entferne und nur CP SIC und nen Traktor mit SIC drin habe besteht das Problem noch.

**Comment by jason0611** [comment]
Hallo, ich hatte einige Zeit lang dasselbe Problem auf dem Dedi-Server. Letztens habe ich wegen Inkompatibilitäten mit AutoDrive den Mod "FS19_coverAddon" herausgenommen. Jetzt ist mit aufgefallen, dass SIC auch innen wieder reibungslos funktioniert. 
Ich werde das demnächst noch mal im Testspielstand nachstellen, daher zunächst unter Vorbehalt als Anhaltspunkt.

**Comment by N0ah16** [comment]
Habs jetzt auf eine meiner Maustasten gelegt, jetzt funktioniert es.
