### ISSUE TITLE
Ic wont show up ingame 

### ISSUE THREAD

**Issue by mINirSr** [modelleicher/FS19_simpleIC#82]
<Ic wont show up in game. I have tried only with simple-ic and your deutz agrostar 6.61. But it won't show up. Got this error in the log.
  
Warning: Missing l10n 'input_IC_SPACE'
  Warning: Missing l10n 'input_IC_MOUSE'
  Warning: Missing l10n 'input_IC_SPACE'
  Warning: Missing l10n 'input_IC_MOUSE'
  Warning: Tried assigning the binding [(KEY_space), deviceId: KB_MOUSE_DEFAULT, axisComponent: +, index: 1, isActive: true, isShadowed: false isInverted: nil, isDown: false, isUp: false, inputValue: 0] to IC_SPACE to an occupied slot. The new binding has been ignored
  Warning: Tried assigning the binding [(MOUSE_BUTTON_LEFT), deviceId: KB_MOUSE_DEFAULT, axisComponent: +, index: 3, isActive: true, isShadowed: false isInverted: nil, isDown: false, isUp: false, inputValue: 0] to IC_MOUSE to an occupied slot. The new binding has been ignored
  Warning: Tried assigning the binding [(KEY_space), deviceId: KB_MOUSE_DEFAULT, axisComponent: +, index: 1, isActive: true, isShadowed: false isInverted: nil, isDown: false, isUp: false, inputValue: 0] to IC_SPACE to an occupied slot. The new binding has been ignored
  Warning: Tried assigning the binding [(MOUSE_BUTTON_LEFT), deviceId: KB_MOUSE_DEFAULT, axisComponent: +, index: 3, isActive: true, isShadowed: false isInverted: nil, isDown: false, isUp: false, inputValue: 0] to IC_MOUSE to an occupied slot. The new binding has been ignored

**Comment by modelleicher** [comment]
Hi, did you try to reassign the Key Bindings ingame?

**Comment by mINirSr** [comment]
Yea i did it now. Now it works like a charm. Thanks alot, and keep up the great work with the mod!
