### ISSUE TITLE
tool control

### ISSUE THREAD

**Issue by zcaalock** [modelleicher/FS19_simpleIC#93]
can you use this script to control tools? F.e click button inside cabin to lower tool or turn on lights

**Comment by modelleicher** [comment]
Yes indeed have a look at the examples.xml but not all features are fully implemented yet and thus some are missing from that file for now

**Comment by zcaalock** [comment]
i want to set tool up/down (same as press v key) can you say how to do it?

**Comment by modelleicher** [comment]
Have a look at the examples.xml especially the part "attacherControl" ;)

**Comment by zcaalock** [comment]
i have something like this and it`s not working. Normal animation without attacherControl is working fine


`<simpleIC>
        <attacherControl attacherIndex="1" >
            <leverAnimation animationName="toolUp" doNotSynch="false" returnToCenter="true" returnToCenterRaised="true" returnToCenterLowered="true"/>
            <insideTrigger triggerPoint="0>0|12|1" triggerPointSize="0.04"/>
    </simpleIC>
  
  <animations>
        <animation name="toolUp" >
            <part node="0>0|12|0" startTime="0.0" endTime="1.0" startRot="90 0 0" endRot="88.7 0 0" />
        </animation>
</animations>`

edit: cannot instert cone for some reason
![code](https://user-images.githubusercontent.com/24411061/115148422-c5744200-a05f-11eb-995a-9a1d8dbada4c.jpg)

**Comment by modelleicher** [comment]
you're missing an `</attacherControl>` tag to close `<attacherControl ... >`

**Comment by zcaalock** [comment]
it`s not missing, i copied it wrong. Will this code enable tool up/down by clicking leaver in the cabin? This is what i want to archive. What is attacherIndex? i cannot find any documentation on this parameter.

**Comment by modelleicher** [comment]
Yes, this code will lower or raise the Implement which is in the first attacherJoint (attacherIndex="1") when you click the "X"

attacherIndex is the number of the attacherJoint this is related to. Its the same system as with PTO joints, connectionHoses and so on.
![attacherIndices](https://user-images.githubusercontent.com/7594383/115592070-18096480-a2d3-11eb-8dd1-35555d94aec5.jpg)

**Comment by zcaalock** [comment]
ok, thanks for fast answer
